# PYTHON ASSIGNMENT

# NAME: KEERTHIGA.B
# REG NO: 21UAI026


# INHERITANCE
## SINGLE INHERTANCE

In [4]:
# single inheritance using protected access modifier
class emp:
    def __init__(self,name,income):
        #protected data members initialization
        self._name=name
        self._income=income
class hr(emp):
    def display(self):
        print("NAME:",self._name)
        print("INCOME",self._income)
    def dec(self):
        print('I AM A TEAM LEAD')
hrobj=hr('keerthiga',2000000)
hrobj.display()
hrobj.dec()

NAME: keerthiga
INCOME 2000000
I AM A TEAM LEAD


## MULTILEVEL INHERITANCE

In [8]:
class gfather:
    gfname='HI'
    gfage=20
class father(gfather):
    fname='HELLO'
    fage=5
class son(father):
    sname='WELCOME'
    sage=1
sobj=son()
print(sobj.gfname,"\n",sobj.gfage)


HI 
 20


## MULTIPLE INHERITANCE

In [9]:
class father:
    fname='HI'
    fage=10
class mother:
    mname='HELLO'
    mage=12
class son(father,mother):
    sname='WELCOME'
    sage=5
sobj=son()
print("FATHER DETAILS:")
print(sobj.fname,"\n",sobj.fage)
print("\n")
print("MOTHER DETAILS:")
print(sobj.mname,"\n",sobj.mage)

FATHER DETAILS:
HI 
 10


MOTHER DETAILS:
HELLO 
 12


## HIERARCHIAL INHERITANCE

In [13]:
class university:
    uid=100
    uname="XYZ UNIVERSITY"
class arts(university):
    aid=123
    aname="XYZ ARTS & SCIENCE"
class engg(university):
    eid=234
    ename="XYZ ENGINEERING COLLEGE"
class medical(university):
    mid=331
    mname="XYZ MEDICAL COLLEGE & HOSPITAL"
class arch(university):
    arid=445
    arname="XYZ SCHOOL OF ARCHITECTURE"
eobj=engg()
print(eobj.eid,"\n",eobj.ename)

234 
 XYZ ENGINEERING COLLEGE


## HYBRID INHERITANCE

In [15]:
class GrandPa:
    def __init__(self):
        print("Grand Pa")

class Father(GrandPa):
    def __init__(self):
        super().__init__()
        print("Father")

class Mother(GrandPa):
    def __init__(self):
        super().__init__()
        print("Mother")


class child(Father, Mother):
    def __init__(self):
        super().__init__()
        print("Child")

c = child()


Grand Pa
Mother
Father
Child


## ACCESS MODIFIERS

In [16]:
#private inheritance
class emp:
    def __init__(self,eid,name):
        self._eid=eid
        self._name=name
e1=emp(2,'HI')
e1._eid

2

In [17]:
#private data members initialization
class emp:
    def __init__(self,emid,name):
        self.__eid=emid 
        self.__ename=name
e1=emp(1,"VK")

# protected data members initialization
class job:
    def __init__(self,name,role):
        self._name=name 
        self._role=role
    def displaydata(self):
        print("name:",self._name)
        print("role:",self._role)
class hr(job):
    print("WELCOME")
o1=hr('KEERTHI','STUDENT') 
o1.displaydata()



WELCOME
name: KEERTHI
role: STUDENT


In [18]:
#public data members initialization
class emp:
    def __init__(self,name,height,weight):
        self.sname=name # all data members are public by default 
        self.sheight=height # . is used to initialize public data members
        self.sweight=weight
    def display(self):
        print("NAME:",self.sname)
        print("HEIGHT:",self.sheight)
        print("WEIGHT:",self.sweight)
o1=emp('KEERTHIGA',170,53.8)
o1.display()

NAME: KEERTHIGA
HEIGHT: 170
WEIGHT: 53.8


## NUMPY AGGREGATORS

In [21]:
import numpy as np
x=np.array([[1,3,5,2],[5,34,54,5],[9,10,11,12]])
print(np.max(x),np.min(x),np.sum(x))

54 1 151


In [22]:
m=np.random.randint(1,50,(2,4))
print(m)
print(m.sum())
print("sum row-wise:",np.sum(x,axis=1))
print("sum col-wise:",np.sum(x,axis=0))
print("max element of each col:",np.max(x,axis=0))
print("min element of each col:",np.min(x,axis=0))


[[37 39  2 39]
 [ 6 18 19 22]]
182
sum row-wise: [11 98 42]
sum col-wise: [15 47 70 19]
max element of each col: [ 9 34 54 12]
min element of each col: [1 3 5 2]


In [23]:
import numpy as np
print(np.product([[1,6],[2,4]]))
print(np.mean([[2,6],[6,8]]))
print(np.std([[2,4],[6,8]]))
print(np.var([[2,2],[6,8]]))
x=np.array([[2,4],[6,8]])
print(np.argmax([1,2,3,4]))
print(np.argmin([1,2,3,4]))
b=np.array([True,True,True,False])
print(np.all(b))
print(np.any(b))
print(np.median([1,2,3,4,5]))

48
5.5
2.23606797749979
6.75
3
0
False
True
3.0


## COMPARISION,MASKS AND BOOLEAN ARRAYS IN NUMPY

In [24]:
#boolean operations
import numpy as np
x=np.array([1,2,3,4,5])
print(x<2)
print(x>2)
print(x<=2)
print(x>=2)
print(x!=2)
print(x==2)

[ True False False False False]
[False False  True  True  True]
[ True  True False False False]
[False  True  True  True  True]
[ True False  True  True  True]
[False  True False False False]


In [25]:
3*x==(x**3)

array([False, False, False, False, False])

In [26]:
bool(23 and 0)

False

In [28]:
x=np.array([1,0,1,0,1,1],dtype=bool)
y=np.array([1,1,1,0,1,0],dtype=bool)

In [30]:
x&y

array([ True, False,  True, False,  True, False])

In [31]:
x|y

array([ True,  True,  True, False,  True,  True])

In [32]:
x!=y

array([False,  True, False, False, False,  True])

In [33]:
x^y

array([False,  True, False, False, False,  True])

In [35]:
np.all(x) 

False

In [36]:
np.any(y)

True

## EXCEPTION HANDLING

In [42]:
#zero division error
def fun(a,b):
    try:
        c=a+b/(a-b)
    except ZeroDivisionError:
        print("Error due to divided by 0")
        
    else:
        print(c)
    finally:
        print("error handling learnt succesfully")
fun(2,1)      

    

3.0
error handling learnt succesfully


In [43]:
cgpa=9
try:
    if(cgpa>8.5):
        print("distinction")
except SyntaxError:
    print("syntax error")



distinction


In [39]:
list1 = ['x',1, 2, 3,-9.6]
try: 
    print ("Second element =",list1[1])
    print ("Sixth element =",list1[5]) #trying to access out of range element
  
except:
    print ("An error occurred")

Second element = 1
An error occurred


In [44]:
def func1(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("dividing a/b is 0")
    else:
        print (c)  
        
func1(1,1)
func1(3,1)

dividing a/b is 0
2.0


In [45]:
try:
    raise NameError("Hi hello") # Raise Error
except NameError:
    print ("An exception")
    

An exception
